---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: true
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

# Mikrotik exporter configuration. (Also requires `monitoring_enable`)
mikrotik_enable: true
mikrotik_name: MikroTik
mikrotik_address: router-ip-address
mikrotik_port: 8728
mikrotik_user: prometheus
mikrotik_pass: "change-this-password"

# Proxmox exporter configuration. (Also requires `monitoring_enable`)
pve_enable: true
pve_user: prometheus@pve
pve_token_name: pve-token-id
pve_token_secret: pve-token-secret
pve_target: pve-ip-address
pve_verify_ssl: false